In [1]:
import torch
import torch.linalg as tla
torch.set_printoptions(sci_mode=True)

In [2]:
# A = torch.tensor([[1,2,4],[1,4,8]],dtype=torch.float)
A = torch.tensor([[2,4],[4,8]],dtype=torch.float)

print(A)
print(f'Rank: {tla.matrix_rank(A)}')

tensor([[2.0000e+00, 4.0000e+00],
        [4.0000e+00, 8.0000e+00]])
Rank: 1


In [3]:
A_svd = tla.svd(A,full_matrices= True)
nA = A_svd.Vh.t()[:,-1].reshape(-1,1)
print('Null space:')
nA

Null space:


tensor([[-8.9443e-01],
        [4.4721e-01]])

In [4]:
A@nA

tensor([[2.3842e-07],
        [4.7684e-07]])

In [5]:
b = torch.rand(2,1)
b

tensor([[2.2037e-01],
        [8.7207e-01]])

In [6]:
x = torch.linalg.lstsq(A,b).solution
print(x)
print(x.norm())

tensor([[3.9290e-02],
        [7.8580e-02]])
tensor(8.7855e-02)


In [7]:
print('A @ x:')
print(A@x)
print('A @ (x + alpha*nA)')
print(A@(x+torch.rand(1)*nA))

A @ x:
tensor([[3.9290e-01],
        [7.8580e-01]])
A @ (x + alpha*nA)
tensor([[3.9290e-01],
        [7.8580e-01]])


In [10]:
A_pinv = A.pinverse()
print(A_pinv)
x_pinv = A.pinverse()@b
x_pinv

tensor([[   6.0483e+06,   -3.0242e+06],
        [  -3.0242e+06,    1.5121e+06]])


tensor([[  -1.3044e+06],
        [   6.5222e+05]])

In [9]:
A@x_pinv

tensor([[1.0000e+00],
        [2.0000e+00]])