In [35]:
import torch
torch.set_printoptions(sci_mode=False)

In [28]:
A = torch.tensor(([1,3,0,2],[0,0,1,4],[1,3,1,6]),dtype=torch.float)
b = torch.tensor([1,6,7],dtype=torch.float).reshape(-1,1)
print(f'A:{A}')
print(f'b:{b}')

A:tensor([[1., 3., 0., 2.],
        [0., 0., 1., 4.],
        [1., 3., 1., 6.]])
b:tensor([[1.],
        [6.],
        [7.]])
tensor([[1., 3., 0., 2.],
        [0., 0., 1., 4.],
        [1., 3., 1., 6.]])


In [30]:
sol = torch.linalg.lstsq(A,b)
sol

torch.return_types.linalg_lstsq(
solution=tensor([[0.1524],
        [0.4571],
        [0.0762],
        [0.6095]]),
residuals=tensor([]),
rank=tensor(1),
singular_values=tensor([]))

In [37]:
A_svd = torch.linalg.svd(A,full_matrices= True)
print(A_svd)
nA = A_svd.Vh[-2:,:].t()
print('Null space:')
nA

torch.return_types.linalg_svd(
U=tensor([[-0.3788, -0.7233, -0.5774],
        [-0.4370,  0.6897, -0.5774],
        [-0.8158, -0.0336,  0.5774]]),
S=tensor([    8.4028,     2.7190,     0.0000]),
Vh=tensor([[-0.1422, -0.4265, -0.1491, -0.8807],
        [-0.2784, -0.8351,  0.2413,  0.4085],
        [-0.9326,  0.3333,  0.1346, -0.0337],
        [-0.1807, -0.0980, -0.9494,  0.2374]]))
Null space:


tensor([[-0.9326, -0.1807],
        [ 0.3333, -0.0980],
        [ 0.1346, -0.9494],
        [-0.0337,  0.2374]])

In [36]:
A@nA

tensor([[     0.0000,      0.0000],
        [    -0.0000,      0.0000],
        [    -0.0000,      0.0000]])